# Changing the port for the GraphQL server
server:
  port: 8180


# Changing the server path
#graphql:
#  url: /my/updated/graphql/path

# https://docs.spring.io/spring-security-oauth2-boot/docs/current/reference/html5/#oauth2-boot-resource-server-token-info
security:
  oauth2:
    client:
      client-id: clientId
      client-secret: secret
    resource:
#      user-info-uri: http://localhost:8181/profile/me
      introspection-uri: http://localhost:8181/oauth/check_token
#      introspection-client-id: clientId
#      introspection-client-secret: secret

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true